title: App Hack
description: Android / IOS

url: http://howedeng.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: howedeng
  #  twitter: brianmaierjr
  #  facebook: brianmaierjr
   email: howejee@gmail.com

google_analytics: "UA-58263416-1"
